<a href="https://colab.research.google.com/github/OZZYTA/IntensivoCiclo1/blob/main/1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

Es una librería en la que se define un tipo de dato que representa matrices multidimensionales. Además incluye algunas funcionalidades básicas para trabajar con ellas. Numpy es una librería con una amplia tradición en Python, es estable y muy rápida.

In [1]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [3]:
frutas= ("Limon","Naranja","Maracuya","Guayaba","Fresas","Piña")
frutas

('Limon', 'Naranja', 'Maracuya', 'Guayaba', 'Fresas', 'Piña')

In [4]:
frutas=np.array(frutas)
frutas

array(['Limon', 'Naranja', 'Maracuya', 'Guayaba', 'Fresas', 'Piña'],
      dtype='<U8')

In [5]:
frutas=np.delete(frutas,[4])
frutas

array(['Limon', 'Naranja', 'Maracuya', 'Guayaba', 'Piña'], dtype='<U8')

In [8]:
paises=np.array(["Colombia","Panamá","Brasil","Venezuela","Argentina","Chile"]) #Creamos un arreglo de paises
capitales=np.array(["Bogotá","Ciudad de Panamá","Brasilia","Caracas","Buenos Aires","Santiago de Chile"]) #Creamos arreglo con las capitales

pais=input("De qué pais deseas saber la capital?: ")
posicion=np.where(paises==pais)
print(f"La capital de {pais} es: {capitales[posicion]}")

De qué pais deseas saber la capital?: Colombia
La capital de Colombia es: ['Bogotá']


In [9]:
#Numeros

lista=[25,12,15,66,12,5]
vector=np.array(lista)
lista

[25, 12, 15, 66, 12, 5]

In [11]:
print("Vector Original")
vector

Vector Original


array([25, 12, 15, 66, 12,  5])

In [13]:
print("Vector original sumando 1 a cada elemento:")
vector+1

Vector original sumando 1 a cada elemento:


array([26, 13, 16, 67, 13,  6])

In [14]:
print("Vector original multiplicando *5 cada elemento:")
vector*5

Vector original multiplicando *5 cada elemento:


array([125,  60,  75, 330,  60,  25])

In [15]:
print("Suma de todos los elementos del vector")
np.sum(vector)

Suma de todos los elementos del vector


135

In [16]:
print("Promedio todos los elementos del vector")
np.mean(vector)

Promedio todos los elementos del vector


22.5

In [17]:
np.sum(vector)/len(vector)

22.5

In [18]:
lista*5

[25,
 12,
 15,
 66,
 12,
 5,
 25,
 12,
 15,
 66,
 12,
 5,
 25,
 12,
 15,
 66,
 12,
 5,
 25,
 12,
 15,
 66,
 12,
 5,
 25,
 12,
 15,
 66,
 12,
 5]